// peru-data.tsx

export const UBIGEO_PERU: Record<string, Record<string, string[]>> = {
    "AMAZONAS": {
        "CHACHAPOYAS": [
            "CHACHAPOYAS",
            "ASUNCION",
            "BALSAS",
            "CHETO",
            "CHILIQUIN",
            "CHUQUIBAMBA",
            "GRANADA",
            "HUANCAS",
            "LA JALCA",
            "LEIMEBAMBA",
            "LEVANTO",
            "MAGDALENA",
            "MARISCAL CASTILLA",
            "MOLINOPAMPA",
            "MONTEVIDEO",
            "OLLEROS",
            "QUINJALCA",
            "SAN FRANCISCO DE DAGUAS",
            "SAN ISIDRO DE MAINO",
            "SOLOCO",
            "SONCHE"
        ],
        "BAGUA": [
            "LA PECA",
            "ARAMANGO",
            "COPALLIN",
            "EL PARCO",
            "BAGUA",
            "IMAZA"
        ],
        "BONGARA": [
            "JUMBILLA",
            "COROSHA",
            "CUISPES",
            "CHISQUILLA",
            "CHURUJA",
            "FLORIDA",
            "RECTA",
            "SAN CARLOS",
            "SHIPASBAMBA",
            "VALERA",
            "YAMBRASBAMBA",
            "JAZAN"
        ],
        "LUYA": [
            "LAMUD",
            "CAMPORREDONDO",
            "COCABAMBA",
            "COLCAMAR",
            "CONILA",
            "INGUILPATA",
            "LONGUITA",
            "LONYA CHICO",
            "LUYA",
            "LUYA VIEJO",
            "MARIA",
            "OCALLI",
            "OCUMAL",
            "PISUQUIA",
            "SAN CRISTOBAL",
            "SAN FRANCISCO DE YESO",
            "SAN JERONIMO",
            "SAN JUAN DE LOPECANCHA",
            "SANTA CATALINA",
            "SANTO TOMAS",
            "TINGO",
            "TRITA",
            "PROVIDENCIA"
        ],
        "RODRIGUEZ DE MENDOZA": [
            "SAN NICOLAS",
            "COCHAMAL",
            "CHIRIMOTO",
            "HUAMBO",
            "LIMABAMBA",
            "LONGAR",
            "MILPUC",
            "MARISCAL BENAVIDES",
            "OMIA",
            "SANTA ROSA",
            "TOTORA",
            "VISTA ALEGRE"
        ],
        "CONDORCANQUI": [
            "NIEVA",
            "RIO SANTIAGO",
            "EL CENEPA"
        ],
        "UTCUBAMBA": [
            "BAGUA GRANDE",
            "CAJARURO",
            "CUMBA",
            "EL MILAGRO",
            "JAMALCA",
            "LONYA GRANDE",
            "YAMON"
        ]
    },
    "ANCASH": {
        "HUARAZ": [
            "HUARAZ",
            "INDEPENDENCIA",
            "COCHABAMBA",
            "COLCABAMBA",
            "HUANCHAY",
            "JANGAS",
            "LA LIBERTAD",
            "OLLEROS",
            "PAMPAS GRANDE",
            "PARIACOTO",
            "PIRA",
            "TARICA"
        ],
        "AIJA": [
            "AIJA",
            "CORIS",
            "HUACLLAN",
            "LA MERCED",
            "SUCCHA"
        ],
        "BOLOGNESI": [
            "CHIQUIAN",
            "ABELARDO PARDO LEZAMETA",
            "AQUIA",
            "CAJACAY",
            "HUAYLLACAYAN",
            "HUASTA",
            "MANGAS",
            "PACLLON",
            "SAN MIGUEL DE CORPANQUI",
            "TICLLOS",
            "ANTONIO RAYMONDI",
            "CANIS",
            "COLQUIOC",
            "LA PRIMAVERA",
            "HUALLANCA"
        ],
        "CARHUAZ": [
            "CARHUAZ",
            "ACOPAMPA",
            "AMASHCA",
            "ANTA",
            "ATAQUERO",
            "MARCARA",
            "PARIAHUANCA",
            "SAN MIGUEL DE ACO",
            "SHILLA",
            "TINCO",
            "YUNGAR"
        ],
        "CASMA": [
            "CASMA",
            "BUENA VISTA ALTA",
            "COMANDANTE NOEL",
            "YAUTAN"
        ],
        "CORONGO": [
            "CORONGO",
            "ACO",
            "BAMBAS",
            "CUSCA",
            "LA PAMPA",
            "YANAC",
            "YUPAN"
        ],
        "HUAYLAS": [
            "CARAZ",
            "HUALLANCA",
            "HUATA",
            "HUAYLAS",
            "MATO",
            "PAMPAROMAS",
            "PUEBLO LIBRE",
            "SANTA CRUZ",
            "YURACMARCA",
            "SANTO TORIBIO"
        ],
        "HUARI": [
            "HUARI",
            "CAJAY",
            "CHAVIN DE HUANTAR",
            "HUACACHI",
            "HUACHIS",
            "HUACCHIS",
            "HUANTAR",
            "MASIN",
            "PAUCAS",
            "PONTO",
            "RAHUAPAMPA",
            "RAPAYAN",
            "SAN MARCOS",
            "SAN PEDRO DE CHANA",
            "UCO",
            "ANRA"
        ],
        "MARISCAL LUZURIAGA": [
            "PISCOBAMBA",
            "CASCA",
            "LUCMA",
            "FIDEL OLIVAS ESCUDERO",
            "LLAMA",
            "LLUMPA",
            "MUSGA",
            "ELEAZAR GUZMAN BARRON"
        ],
        "PALLASCA": [
            "CABANA",
            "BOLOGNESI",
            "CONCHUCOS",
            "HUACASCHUQUE",
            "HUANDOVAL",
            "LACABAMBA",
            "LLAPO",
            "PALLASCA",
            "PAMPAS",
            "SANTA ROSA",
            "TAUCA"
        ],
        "POMABAMBA": [
            "POMABAMBA",
            "HUAYLLAN",
            "PAROBAMBA",
            "QUINUABAMBA"
        ],
        "RECUAY": [
            "RECUAY",
            "COTAPARACO",
            "HUAYLLAPAMPA",
            "MARCA",
            "PAMPAS CHICO",
            "PARARIN",
            "TAPACOCHA",
            "TICAPAMPA",
            "LLACLLIN",
            "CATAC"
        ],
        "SANTA": [
            "CHIMBOTE",
            "CACERES DEL PERU",
            "MACATE",
            "MORO",
            "NEPEÑA",
            "SAMANCO",
            "SANTA",
            "COISHCO",
            "NUEVO CHIMBOTE"
        ],
        "SIHUAS": [
            "SIHUAS",
            "ALFONSO UGARTE",
            "CHINGALPO",
            "HUAYLLABAMBA",
            "QUICHES",
            "SICSIBAMBA",
            "ACOBAMBA",
            "CASHAPAMPA",
            "RAGASH",
            "SAN JUAN"
        ],
        "YUNGAY": [
            "YUNGAY",
            "CASCAPARA",
            "MANCOS",
            "MATACOTO",
            "QUILLO",
            "RANRAHIRCA",
            "SHUPLUY",
            "YANAMA"
        ],
        "ANTONIO RAYMONDI": [
            "LLAMELLIN",
            "ACZO",
            "CHACCHO",
            "CHINGAS",
            "MIRGAS",
            "SAN JUAN DE RONTOY"
        ],
        "CARLOS FERMIN FITZCARRALD": [
            "SAN LUIS",
            "YAUYA",
            "SAN NICOLAS"
        ],
        "ASUNCION": [
            "CHACAS",
            "ACOCHACA"
        ],
        "HUARMEY": [
            "HUARMEY",
            "COCHAPETI",
            "HUAYAN",
            "MALVAS",
            "CULEBRAS"
        ],
        "OCROS": [
            "ACAS",
            "CAJAMARQUILLA",
            "CARHUAPAMPA",
            "COCHAS",
            "CONGAS",
            "LLIPA",
            "OCROS",
            "SAN CRISTOBAL DE RAJAN",
            "SAN PEDRO",
            "SANTIAGO DE CHILCAS"
        ]
    },
    "APURIMAC": {
        "ABANCAY": [
            "ABANCAY",
            "CIRCA",
            "CURAHUASI",
            "CHACOCHE",
            "HUANIPACA",
            "LAMBRAMA",
            "PICHIRHUA",
            "SAN PEDRO DE CACHORA",
            "TAMBURCO"
        ],
        "AYMARAES": [
            "CHALHUANCA",
            "CAPAYA",
            "CARAYBAMBA",
            "COLCABAMBA",
            "COTARUSE",
            "CHAPIMARCA",
            "HUAYLLU",
            "LUCRE",
            "POCOHUANCA",
            "SAÑAYCA",
            "SORAYA",
            "TAPAIRIHUA",
            "TINTAY",
            "TORAYA",
            "YANACA",
            "SAN JUAN DE CHACÑA",
            "JUSTO APU SAHUARAURA"
        ],
        "ANDAHUAYLAS": [
            "ANDAHUAYLAS",
            "ANDARAPA",
            "CHIARA",
            "HUANCARAMA",
            "HUANCARAY",
            "KISHUARA",
            "PACOBAMBA",
            "PAMPACHIRI",
            "SAN ANTONIO DE CACHI",
            "SAN JERONIMO",
            "TALAVERA",
            "TURPO",
            "PACUCHA",
            "POMACOCHA",
            "SANTA MARIA DE CHICMO",
            "TUMAY HUARACA",
            "HUAYANA",
            "SAN MIGUEL DE CHACCRAMPA",
            "KAQUIABAMBA",
            "JOSE MARIA ARGUEDAS"
        ],
        "ANTABAMBA": [
            "ANTABAMBA",
            "EL ORO",
            "HUAQUIRCA",
            "JUAN ESPINOZA MEDRANO",
            "OROPESA",
            "PACHACONAS",
            "SABAINO"
        ],
        "COTABAMBAS": [
            "TAMBOBAMBA",
            "COYLLURQUI",
            "COTABAMBAS",
            "HAQUIRA",
            "MARA",
            "CHALLHUAHUACHO"
        ],
        "GRAU": [
            "CHUQUIBAMBILLA",
            "CURPAHUASI",
            "HUAYLLATI",
            "MAMARA",
            "MARISCAL GAMARRA",
            "MICAELA BASTIDAS",
            "PROGRESO",
            "PATAYPAMPA",
            "SAN ANTONIO",
            "TURPAY",
            "VILCABAMBA",
            "VIRUNDO",
            "SANTA ROSA",
            "CURASCO"
        ],
        "CHINCHEROS": [
            "CHINCHEROS",
            "ONGOY",
            "OCOBAMBA",
            "COCHARCAS",
            "ANCO-HUALLO",
            "HUACCANA",
            "URANMARCA",
            "RANRACANCHA",
            "ROCCHACC",
            "EL PORVENIR",
            "LOS CHANKAS",
            "AHUAYRO"
        ]
    },
    "AREQUIPA": {
        "AREQUIPA": [
            "AREQUIPA",
            "CAYMA",
            "CERRO COLORADO",
            "CHARACATO",
            "CHIGUATA",
            "LA JOYA",
            "MIRAFLORES",
            "MOLLEBAYA",
            "PAUCARPATA",
            "POCSI",
            "POLOBAYA",
            "QUEQUEÑA",
            "SABANDIA",
            "SACHACA",
            "SAN JUAN DE SIGUAS",
            "SAN JUAN DE TARUCANI",
            "SANTA ISABEL DE SIGUAS",
            "SANTA RITA DE SIGUAS",
            "SOCABAYA",
            "TIABAYA",
            "UCHUMAYO",
            "VITOR",
            "YANAHUARA",
            "YARABAMBA",
            "YURA",
            "MARIANO MELGAR",
            "JACOBO HUNTER",
            "ALTO SELVA ALEGRE",
            "JOSE LUIS BUSTAMANTE Y RIVERO"
        ],
        "CAYLLOMA": [
            "CHIVAY",
            "ACHOMA",
            "CABANACONDE",
            "CAYLLOMA",
            "CALLALLI",
            "COPORAQUE",
            "HUAMBO",
            "HUANCA",
            "ICHUPAMPA",
            "LARI",
            "LLUTA",
            "MACA",
            "MADRIGAL",
            "SAN ANTONIO DE CHUCA",
            "SIBAYO",
            "TAPAY",
            "TISCO",
            "TUTI",
            "YANQUE",
            "MAJES"
        ],
        "CAMANA": [
            "CAMANA",
            "JOSE MARIA QUIMPER",
            "MARIANO NICOLAS VALCARCEL",
            "MARISCAL CACERES",
            "NICOLAS DE PIEROLA",
            "OCOÑA",
            "QUILCA",
            "SAMUEL PASTOR"
        ],
        "CARAVELI": [
            "CARAVELI",
            "ACARI",
            "ATICO",
            "ATIQUIPA",
            "BELLA UNION",
            "CAHUACHO",
            "CHALA",
            "CHAPARRA",
            "HUANUHUANU",
            "JAQUI",
            "LOMAS",
            "QUICACHA",
            "YAUCA"
        ],
        "CASTILLA": [
            "APLAO",
            "ANDAGUA",
            "AYO",
            "CHACHAS",
            "CHILCAYMARCA",
            "CHOCO",
            "HUANCARQUI",
            "MACHAGUAY",
            "ORCOPAMPA",
            "PAMPACOLCA",
            "TIPAN",
            "URACA",
            "UÑON",
            "VIRACO"
        ],
        "CONDESUYOS": [
            "CHUQUIBAMBA",
            "ANDARAY",
            "CAYARANI",
            "CHICHAS",
            "IRAY",
            "SALAMANCA",
            "YANAQUIHUA",
            "RIO GRANDE"
        ],
        "ISLAY": [
            "MOLLENDO",
            "COCACHACRA",
            "DEAN VALDIVIA",
            "ISLAY",
            "MEJIA",
            "PUNTA DE BOMBON"
        ],
        "LA UNION": [
            "COTAHUASI",
            "ALCA",
            "CHARCANA",
            "HUAYNACOTAS",
            "PAMPAMARCA",
            "PUYCA",
            "QUECHUALLA",
            "SAYLA",
            "TAURIA",
            "TOMEPAMPA",
            "TORO"
        ]
    },
    "AYACUCHO": {
        "HUAMANGA": [
            "AYACUCHO",
            "ACOS VINCHOS",
            "CARMEN ALTO",
            "CHIARA",
            "QUINUA",
            "SAN JOSE DE TICLLAS",
            "SAN JUAN BAUTISTA",
            "SANTIAGO DE PISCHA",
            "VINCHOS",
            "TAMBILLO",
            "ACOCRO",
            "SOCOS",
            "OCROS",
            "PACAYCASA",
            "JESUS NAZARENO",
            "ANDRES AVELINO CACERES DORREGARAY"
        ],
        "CANGALLO": [
            "CANGALLO",
            "CHUSCHI",
            "LOS MOROCHUCOS",
            "PARAS",
            "TOTOS",
            "MARIA PARADO DE BELLIDO"
        ],
        "HUANTA": [
            "HUANTA",
            "AYAHUANCO",
            "HUAMANGUILLA",
            "IGUAIN",
            "LURICOCHA",
            "SANTILLANA",
            "SIVIA",
            "LLOCHEGUA",
            "CANAYRE",
            "UCHURACCAY",
            "PUCACOLPA",
            "CHACA",
            "PUTIS"
        ],
        "LA MAR": [
            "SAN MIGUEL",
            "ANCO",
            "AYNA",
            "CHILCAS",
            "CHUNGUI",
            "TAMBO",
            "LUIS CARRANZA",
            "SANTA ROSA",
            "SAMUGARI",
            "ANCHIHUAY",
            "ORONCCOY",
            "UNION PROGRESO",
            "RIO MAGDALENA",
            "NINABAMBA",
            "PATIBAMBA"
        ],
        "LUCANAS": [
            "PUQUIO",
            "AUCARA",
            "CABANA",
            "CARMEN SALCEDO",
            "CHAVIÑA",
            "CHIPAO",
            "HUAC-HUAS",
            "LARAMATE",
            "LEONCIO PRADO",
            "LUCANAS",
            "LLAUTA",
            "OCAÑA",
            "OTOCA",
            "SANCOS",
            "SAN JUAN",
            "SAN PEDRO",
            "SANTA ANA DE HUAYCAHUACHO",
            "SANTA LUCIA",
            "SAISA",
            "SAN PEDRO DE PALCO",
            "SAN CRISTOBAL"
        ],
        "PARINACOCHAS": [
            "CORACORA",
            "CORONEL CASTAÑEDA",
            "CHUMPI",
            "PACAPAUSA",
            "PULLO",
            "PUYUSCA",
            "SAN FRANCISCO DE RAVACAYCO",
            "UPAHUACHO"
        ],
        "VICTOR FAJARDO": [
            "HUANCAPI",
            "ALCAMENCA",
            "APONGO",
            "CANARIA",
            "CAYARA",
            "COLCA",
            "HUAYA",
            "HUAMANQUIQUIA",
            "HUANCARAYLLA",
            "SARHUA",
            "VILCANCHOS",
            "ASQUIPATA"
        ],
        "HUANCA SANCOS": [
            "SANCOS",
            "SACSAMARCA",
            "SANTIAGO DE LUCANAMARCA",
            "CARAPO"
        ],
        "VILCAS HUAMAN": [
            "VILCAS HUAMAN",
            "VISCHONGO",
            "ACCOMARCA",
            "CARHUANCA",
            "CONCEPCION",
            "HUAMBALPA",
            "SAURAMA",
            "INDEPENDENCIA"
        ],
        "PAUCAR DEL SARA SARA": [
            "PAUSA",
            "COLTA",
            "CORCULLA",
            "LAMPA",
            "MARCABAMBA",
            "OYOLO",
            "PARARCA",
            "SAN JAVIER DE ALPABAMBA",
            "SAN JOSE DE USHUA",
            "SARA SARA"
        ],
        "SUCRE": [
            "QUEROBAMBA",
            "BELEN",
            "CHALCOS",
            "SAN SALVADOR DE QUIJE",
            "PAICO",
            "SANTIAGO DE PAUCARAY",
            "SAN PEDRO DE LARCAY",
            "SORAS",
            "HUACAÑA",
            "CHILCAYOC",
            "MORCOLLA"
        ]
    },
    "CAJAMARCA": {
        "CAJAMARCA": [
            "CAJAMARCA",
            "ASUNCION",
            "COSPAN",
            "CHETILLA",
            "ENCAÑADA",
            "JESUS",
            "LOS BAÑOS DEL INCA",
            "LLACANORA",
            "MAGDALENA",
            "MATARA",
            "NAMORA",
            "SAN JUAN"
        ],
        "CAJABAMBA": [
            "CAJABAMBA",
            "CACHACHI",
            "CONDEBAMBA",
            "SITACOCHA"
        ],
        "CELENDIN": [
            "CELENDIN",
            "CORTEGANA",
            "CHUMUCH",
            "HUASMIN",
            "JORGE CHAVEZ",
            "JOSE GALVEZ",
            "MIGUEL IGLESIAS",
            "OXAMARCA",
            "SOROCHUCO",
            "SUCRE",
            "UTCO",
            "LA LIBERTAD DE PALLAN"
        ],
        "CONTUMAZA": [
            "CONTUMAZA",
            "CHILETE",
            "GUZMANGO",
            "SAN BENITO",
            "CUPISNIQUE",
            "TANTARICA",
            "YONAN",
            "SANTA CRUZ DE TOLEDO"
        ],
        "CUTERVO": [
            "CUTERVO",
            "CALLAYUC",
            "CUJILLO",
            "CHOROS",
            "LA RAMADA",
            "PIMPINGOS",
            "QUEROCOTILLO",
            "SAN ANDRES DE CUTERVO",
            "SAN JUAN DE CUTERVO",
            "SAN LUIS DE LUCMA",
            "SANTA CRUZ",
            "SANTO DOMINGO DE LA CAPILLA",
            "SANTO TOMAS",
            "SOCOTA",
            "TORIBIO CASANOVA"
        ],
        "CHOTA": [
            "CHOTA",
            "ANGUIA",
            "COCHABAMBA",
            "CONCHAN",
            "CHADIN",
            "CHIGUIRIP",
            "CHIMBAN",
            "HUAMBOS",
            "LAJAS",
            "LLAMA",
            "MIRACOSTA",
            "PACCHA",
            "PION",
            "QUEROCOTO",
            "TACABAMBA",
            "TOCMOCHE",
            "SAN JUAN DE LICUPIS",
            "CHOROPAMPA",
            "CHALAMARCA"
        ],
        "HUALGAYOC": [
            "BAMBAMARCA",
            "CHUGUR",
            "HUALGAYOC"
        ],
        "JAEN": [
            "JAEN",
            "BELLAVISTA",
            "COLASAY",
            "CHONTALI",
            "POMAHUACA",
            "PUCARA",
            "SALLIQUE",
            "SAN FELIPE",
            "SAN JOSE DEL ALTO",
            "SANTA ROSA",
            "LAS PIRIAS",
            "HUABAL"
        ],
        "SANTA CRUZ": [
            "SANTA CRUZ",
            "CATACHE",
            "CHANCAYBAÑOS",
            "LA ESPERANZA",
            "NINABAMBA",
            "PULAN",
            "SEXI",
            "UTICYACU",
            "YAUYUCAN",
            "ANDABAMBA",
            "SAUCEPAMPA"
        ],
        "SAN MIGUEL": [
            "SAN MIGUEL",
            "CALQUIS",
            "LA FLORIDA",
            "LLAPA",
            "NANCHOC",
            "NIEPOS",
            "SAN GREGORIO",
            "SAN SILVESTRE DE COCHAN",
            "EL PRADO",
            "UNION AGUA BLANCA",
            "TONGOD",
            "CATILLUC",
            "BOLIVAR"
        ],
        "SAN IGNACIO": [
            "SAN IGNACIO",
            "CHIRINOS",
            "HUARANGO",
            "NAMBALLE",
            "LA COIPA",
            "SAN JOSE DE LOURDES",
            "TABACONAS"
        ],
        "SAN MARCOS": [
            "PEDRO GALVEZ",
            "ICHOCAN",
            "GREGORIO PITA",
            "JOSE MANUEL QUIROZ",
            "EDUARDO VILLANUEVA",
            "JOSE SABOGAL",
            "CHANCAY"
        ],
        "SAN PABLO": [
            "SAN PABLO",
            "SAN BERNARDINO",
            "SAN LUIS",
            "TUMBADEN"
        ]
    },
    "CUSCO": {
        "CUSCO": [
            "CUSCO",
            "CCORCA",
            "POROY",
            "SAN JERONIMO",
            "SAN SEBASTIAN",
            "SANTIAGO",
            "SAYLLA",
            "WANCHAQ"
        ],
        "ACOMAYO": [
            "ACOMAYO",
            "ACOPIA",
            "ACOS",
            "POMACANCHI",
            "RONDOCAN",
            "SANGARARA",
            "MOSOC LLACTA"
        ],
        "ANTA": [
            "ANTA",
            "CHINCHAYPUJIO",
            "HUAROCONDO",
            "LIMATAMBO",
            "MOLLEPATA",
            "PUCYURA",
            "ZURITE",
            "CACHIMAYO",
            "ANCAHUASI"
        ],
        "CALCA": [
            "CALCA",
            "COYA",
            "LAMAY",
            "LARES",
            "PISAC",
            "SAN SALVADOR",
            "TARAY",
            "YANATILE"
        ],
        "CANAS": [
            "YANAOCA",
            "CHECCA",
            "KUNTURKANKI",
            "LANGUI",
            "LAYO",
            "PAMPAMARCA",
            "QUEHUE",
            "TUPAC AMARU"
        ],
        "CANCHIS": [
            "SICUANI",
            "COMBAPATA",
            "CHECACUPE",
            "MARANGANI",
            "PITUMARCA",
            "SAN PABLO",
            "SAN PEDRO",
            "TINTA"
        ],
        "CHUMBIVILCAS": [
            "SANTO TOMAS",
            "CAPACMARCA",
            "COLQUEMARCA",
            "CHAMACA",
            "LIVITACA",
            "LLUSCO",
            "QUIÑOTA",
            "VELILLE"
        ],
        "ESPINAR": [
            "ESPINAR",
            "CONDOROMA",
            "COPORAQUE",
            "OCORURO",
            "PALLPATA",
            "PICHIGUA",
            "SUYCKUTAMBO",
            "ALTO PICHIGUA"
        ],
        "LA CONVENCION": [
            "SANTA ANA",
            "ECHARATE",
            "HUAYOPATA",
            "MARANURA",
            "OCOBAMBA",
            "SANTA TERESA",
            "VILCABAMBA",
            "QUELLOUNO",
            "KIMBIRI",
            "PICHARI",
            "INKAWASI",
            "VILLA VIRGEN",
            "VILLA KINTIARINA",
            "MEGANTONI",
            "KUMPIRUSHIATO",
            "CIELO PUNCO",
            "MANITEA",
            "UNION ASHANINKA"
        ],
        "PARURO": [
            "PARURO",
            "ACCHA",
            "CCAPI",
            "COLCHA",
            "HUANOQUITE",
            "OMACHA",
            "YAURISQUE",
            "PACCARITAMBO",
            "PILLPINTO"
        ],
        "PAUCARTAMBO": [
            "PAUCARTAMBO",
            "CAICAY",
            "COLQUEPATA",
            "CHALLABAMBA",
            "KOSÑIPATA",
            "HUANCARANI"
        ],
        "QUISPICANCHI": [
            "URCOS",
            "ANDAHUAYLILLAS",
            "CAMANTI",
            "CCARHUAYO",
            "CCATCA",
            "CUSIPATA",
            "HUARO",
            "LUCRE",
            "MARCAPATA",
            "OCONGATE",
            "OROPESA",
            "QUIQUIJANA"
        ],
        "URUBAMBA": [
            "URUBAMBA",
            "CHINCHERO",
            "HUAYLLABAMBA",
            "MACHUPICCHU",
            "MARAS",
            "OLLANTAYTAMBO",
            "YUCAY"
        ]
    },
    "HUANCAVELICA": {
        "HUANCAVELICA": [
            "HUANCAVELICA",
            "ACOBAMBILLA",
            "ACORIA",
            "CONAYCA",
            "CUENCA",
            "HUACHOCOLPA",
            "HUAYLLAHUARA",
            "IZCUCHACA",
            "LARIA",
            "MANTA",
            "MARISCAL CACERES",
            "MOYA",
            "NUEVO OCCORO",
            "PALCA",
            "PILCHACA",
            "VILCA",
            "YAULI",
            "ASCENSION",
            "HUANDO"
        ],
        "ACOBAMBA": [
            "ACOBAMBA",
            "ANTA",
            "ANDABAMBA",
            "CAJA",
            "MARCAS",
            "PAUCARA",
            "POMACOCHA",
            "ROSARIO"
        ],
        "ANGARAES": [
            "LIRCAY",
            "ANCHONGA",
            "CALLANMARCA",
            "CONGALLA",
            "CHINCHO",
            "HUAYLLAY GRANDE",
            "HUANCA-HUANCA",
            "JULCAMARCA",
            "SAN ANTONIO DE ANTAPARCO",
            "SANTO TOMAS DE PATA",
            "SECCLLA",
            "CCOCHACCASA"
        ],
        "CASTROVIRREYNA": [
            "CASTROVIRREYNA",
            "ARMA",
            "AURAHUA",
            "CAPILLAS",
            "COCAS",
            "CHUPAMARCA",
            "HUACHOS",
            "HUAMATAMBO",
            "MOLLEPAMPA",
            "SAN JUAN",
            "TANTARA",
            "TICRAPO",
            "SANTA ANA"
        ],
        "TAYACAJA": [
            "PAMPAS",
            "ACOSTAMBO",
            "ACRAQUIA",
            "AHUAYCHA",
            "COLCABAMBA",
            "DANIEL HERNANDEZ",
            "HUACHOCOLPA",
            "HUARIBAMBA",
            "ÑAHUIMPUQUIO",
            "PAZOS",
            "QUISHUAR",
            "SALCABAMBA",
            "SAN MARCOS DE ROCCHAC",
            "SURCUBAMBA",
            "TINTAY PUNCU",
            "SALCAHUASI",
            "QUICHUAS",
            "ANDAYMARCA",
            "ROBLE",
            "PICHOS",
            "SANTIAGO DE TUCUMA",
            "LAMBRAS",
            "COCHABAMBA"
        ],
        "HUAYTARA": [
            "AYAVI",
            "CORDOVA",
            "HUAYACUNDO ARMA",
            "HUAYTARA",
            "LARAMARCA",
            "OCOYO",
            "PILPICHACA",
            "QUERCO",
            "QUITO ARMA",
            "SAN ANTONIO DE CUSICANCHA",
            "SAN FRANCISCO DE SANGAYAICO",
            "SAN ISIDRO",
            "SANTIAGO DE CHOCORVOS",
            "SANTIAGO DE QUIRAHUARA",
            "SANTO DOMINGO DE CAPILLAS",
            "TAMBO"
        ],
        "CHURCAMPA": [
            "CHURCAMPA",
            "ANCO",
            "CHINCHIHUASI",
            "EL CARMEN",
            "LA MERCED",
            "LOCROJA",
            "PAUCARBAMBA",
            "SAN MIGUEL DE MAYOCC",
            "SAN PEDRO DE CORIS",
            "PACHAMARCA",
            "COSME"
        ]
    },
    "HUANUCO": {
        "HUANUCO": [
            "HUANUCO",
            "CHINCHAO",
            "CHURUBAMBA",
            "MARGOS",
            "QUISQUI",
            "SAN FRANCISCO DE CAYRAN",
            "SAN PEDRO DE CHAULAN",
            "SANTA MARIA DEL VALLE",
            "YARUMAYO",
            "AMARILIS",
            "PILLCO MARCA",
            "YACUS",
            "SAN PABLO DE PILLAO"
        ],
        "AMBO": [
            "AMBO",
            "CAYNA",
            "COLPAS",
            "CONCHAMARCA",
            "HUACAR",
            "SAN FRANCISCO",
            "SAN RAFAEL",
            "TOMAY KICHWA"
        ],
        "DOS DE MAYO": [
            "LA UNION",
            "CHUQUIS",
            "MARIAS",
            "PACHAS",
            "QUIVILLA",
            "RIPAN",
            "SHUNQUI",
            "SILLAPATA",
            "YANAS"
        ],
        "HUAMALIES": [
            "LLATA",
            "ARANCAY",
            "CHAVIN DE PARIARCA",
            "JACAS GRANDE",
            "JIRCAN",
            "MIRAFLORES",
            "MONZON",
            "PUNCHAO",
            "PUÑOS",
            "SINGA",
            "TANTAMAYO"
        ],
        "MARAÑON": [
            "HUACRACHUCO",
            "CHOLON",
            "SAN BUENAVENTURA",
            "LA MORADA",
            "SANTA ROSA DE ALTO YANAJANCA"
        ],
        "LEONCIO PRADO": [
            "RUPA-RUPA",
            "DANIEL ALOMIA ROBLES",
            "HERMILIO VALDIZAN",
            "LUYANDO",
            "MARIANO DAMASO BERAUN",
            "JOSE CRESPO Y CASTILLO",
            "PUCAYACU",
            "CASTILLO GRANDE",
            "PUEBLO NUEVO",
            "SANTO DOMINGO DE ANDA"
        ],
        "PACHITEA": [
            "PANAO",
            "CHAGLLA",
            "MOLINO",
            "UMARI"
        ],
        "PUERTO INCA": [
            "HONORIA",
            "PUERTO INCA",
            "CODO DEL POZUZO",
            "TOURNAVISTA",
            "YUYAPICHIS"
        ],
        "HUACAYBAMBA": [
            "HUACAYBAMBA",
            "PINRA",
            "CANCHABAMBA",
            "COCHABAMBA"
        ],
        "LAURICOCHA": [
            "JESUS",
            "BAÑOS",
            "SAN FRANCISCO DE ASIS",
            "QUEROPALCA",
            "SAN MIGUEL DE CAURI",
            "RONDOS",
            "JIVIA"
        ],
        "YAROWILCA": [
            "CHAVINILLO",
            "APARICIO POMARES",
            "CAHUAC",
            "CHACABAMBA",
            "JACAS CHICO",
            "OBAS",
            "PAMPAMARCA",
            "CHORAS"
        ]
    },
    "ICA": {
        "ICA": [
            "ICA",
            "LA TINGUIÑA",
            "LOS AQUIJES",
            "PARCONA",
            "PUEBLO NUEVO",
            "SALAS",
            "SAN JOSE DE LOS MOLINOS",
            "SAN JUAN BAUTISTA",
            "SANTIAGO",
            "SUBTANJALLA",
            "YAUCA DEL ROSARIO",
            "TATE",
            "PACHACUTEC",
            "OCUCAJE"
        ],
        "CHINCHA": [
            "CHINCHA ALTA",
            "CHAVIN",
            "CHINCHA BAJA",
            "EL CARMEN",
            "GROCIO PRADO",
            "SAN PEDRO DE HUACARPANA",
            "SUNAMPE",
            "TAMBO DE MORA",
            "ALTO LARAN",
            "PUEBLO NUEVO",
            "SAN JUAN DE YANAC"
        ],
        "NAZCA": [
            "NAZCA",
            "CHANGUILLO",
            "EL INGENIO",
            "MARCONA",
            "VISTA ALEGRE"
        ],
        "PISCO": [
            "PISCO",
            "HUANCANO",
            "HUMAY",
            "INDEPENDENCIA",
            "PARACAS",
            "SAN ANDRES",
            "SAN CLEMENTE",
            "TUPAC AMARU INCA"
        ],
        "PALPA": [
            "PALPA",
            "LLIPATA",
            "RIO GRANDE",
            "SANTA CRUZ",
            "TIBILLO"
        ]
    },
    "JUNIN": {
        "HUANCAYO": [
            "HUANCAYO",
            "CARHUACALLANGA",
            "COLCA",
            "CULLHUAS",
            "CHACAPAMPA",
            "CHICCHE",
            "CHILCA",
            "CHONGOS ALTO",
            "CHUPURO",
            "EL TAMBO",
            "HUACRAPUQUIO",
            "HUALHUAS",
            "HUANCAN",
            "HUASICANCHA",
            "HUAYUCACHI",
            "INGENIO",
            "PARIAHUANCA",
            "PILCOMAYO",
            "PUCARA",
            "QUICHUAY",
            "QUILCAS",
            "SAN AGUSTIN",
            "SAN JERONIMO DE TUNAN",
            "SANTO DOMINGO DE ACOBAMBA",
            "SAÑO",
            "SAPALLANGA",
            "SICAYA",
            "VIQUES"
        ],
        "CONCEPCION": [
            "CONCEPCION",
            "ACO",
            "ANDAMARCA",
            "COMAS",
            "COCHAS",
            "CHAMBARA",
            "HEROINAS TOLEDO",
            "MANZANARES",
            "MARISCAL CASTILLA",
            "MATAHUASI",
            "MITO",
            "NUEVE DE JULIO",
            "ORCOTUNA",
            "SANTA ROSA DE OCOPA",
            "SAN JOSE DE QUERO"
        ],
        "JAUJA": [
            "JAUJA",
            "ACOLLA",
            "APATA",
            "ATAURA",
            "CANCHAYLLO",
            "EL MANTARO",
            "HUAMALI",
            "HUARIPAMPA",
            "HUERTAS",
            "JANJAILLO",
            "JULCAN",
            "LEONOR ORDOÑEZ",
            "LLOCLLAPAMPA",
            "MARCO",
            "MASMA",
            "MOLINOS",
            "MONOBAMBA",
            "MUQUI",
            "MUQUIYAUYO",
            "PACA",
            "PACCHA",
            "PANCAN",
            "PARCO",
            "POMACANCHA",
            "RICRAN",
            "SAN LORENZO",
            "SAN PEDRO DE CHUNAN",
            "SINCOS",
            "TUNAN MARCA",
            "YAULI",
            "CURICACA",
            "MASMA CHICCHE",
            "SAUSA",
            "YAUYOS"
        ],
        "JUNIN": [
            "JUNIN",
            "CARHUAMAYO",
            "ONDORES",
            "ULCUMAYO"
        ],
        "TARMA": [
            "TARMA",
            "ACOBAMBA",
            "HUARICOLCA",
            "HUASAHUASI",
            "LA UNION",
            "PALCA",
            "PALCAMAYO",
            "SAN PEDRO DE CAJAS",
            "TAPO"
        ],
        "YAULI": [
            "LA OROYA",
            "CHACAPALPA",
            "HUAY-HUAY",
            "MARCAPOMACOCHA",
            "MOROCOCHA",
            "PACCHA",
            "SANTA BARBARA DE CARHUACAYAN",
            "SUITUCANCHA",
            "YAULI",
            "SANTA ROSA DE SACCO"
        ],
        "SATIPO": [
            "SATIPO",
            "COVIRIALI",
            "LLAYLLA",
            "MAZAMARI",
            "PAMPA HERMOSA",
            "PANGOA",
            "RIO NEGRO",
            "RIO TAMBO",
            "VIZCATAN DEL ENE"
        ],
        "CHANCHAMAYO": [
            "CHANCHAMAYO",
            "SAN RAMON",
            "VITOC",
            "SAN LUIS DE SHUARO",
            "PICHANAQUI",
            "PERENE"
        ],
        "CHUPACA": [
            "CHUPACA",
            "AHUAC",
            "CHONGOS BAJO",
            "HUACHAC",
            "HUAMANCACA CHICO",
            "SAN JUAN DE YSCOS",
            "SAN JUAN DE JARPA",
            "TRES DE DICIEMBRE",
            "YANACANCHA"
        ]
    },
    "LA LIBERTAD": {
        "TRUJILLO": [
            "TRUJILLO",
            "HUANCHACO",
            "LAREDO",
            "MOCHE",
            "SALAVERRY",
            "SIMBAL",
            "VICTOR LARCO HERRERA",
            "POROTO",
            "EL PORVENIR",
            "LA ESPERANZA",
            "FLORENCIA DE MORA",
            "ALTO TRUJILLO"
        ],
        "BOLIVAR": [
            "BOLIVAR",
            "BAMBAMARCA",
            "CONDORMARCA",
            "LONGOTEA",
            "UCUNCHA",
            "UCHUMARCA"
        ],
        "SANCHEZ CARRION": [
            "HUAMACHUCO",
            "COCHORCO",
            "CURGOS",
            "CHUGAY",
            "MARCABAL",
            "SANAGORAN",
            "SARIN",
            "SARTIMBAMBA"
        ],
        "OTUZCO": [
            "OTUZCO",
            "AGALLPAMPA",
            "CHARAT",
            "HUARANCHAL",
            "LA CUESTA",
            "PARANDAY",
            "SALPO",
            "SINSICAP",
            "USQUIL",
            "MACHE"
        ],
        "PACASMAYO": [
            "SAN PEDRO DE LLOC",
            "GUADALUPE",
            "JEQUETEPEQUE",
            "PACASMAYO",
            "SAN JOSE"
        ],
        "PATAZ": [
            "TAYABAMBA",
            "BULDIBUYO",
            "CHILLIA",
            "HUAYLILLAS",
            "HUANCASPATA",
            "HUAYO",
            "ONGON",
            "PARCOY",
            "PATAZ",
            "PIAS",
            "TAURIJA",
            "URPAY",
            "SANTIAGO DE CHALLAS"
        ],
        "SANTIAGO DE CHUCO": [
            "SANTIAGO DE CHUCO",
            "CACHICADAN",
            "MOLLEBAMBA",
            "MOLLEPATA",
            "QUIRUVILCA",
            "SANTA CRUZ DE CHUCA",
            "SITABAMBA",
            "ANGASMARCA"
        ],
        "ASCOPE": [
            "ASCOPE",
            "CHICAMA",
            "CHOCOPE",
            "SANTIAGO DE CAO",
            "MAGDALENA DE CAO",
            "PAIJAN",
            "RAZURI",
            "CASA GRANDE"
        ],
        "CHEPEN": [
            "CHEPEN",
            "PACANGA",
            "PUEBLO NUEVO"
        ],
        "JULCAN": [
            "JULCAN",
            "CARABAMBA",
            "CALAMARCA",
            "HUASO"
        ],
        "GRAN CHIMU": [
            "CASCAS",
            "LUCMA",
            "MARMOT",
            "SAYAPULLO"
        ],
        "VIRU": [
            "VIRU",
            "CHAO",
            "GUADALUPITO"
        ]
    },
    "LAMBAYEQUE": {
        "CHICLAYO": [
            "CHICLAYO",
            "CHONGOYAPE",
            "ETEN",
            "ETEN PUERTO",
            "LAGUNAS",
            "MONSEFU",
            "NUEVA ARICA",
            "OYOTUN",
            "PICSI",
            "PIMENTEL",
            "REQUE",
            "JOSE LEONARDO ORTIZ",
            "SANTA ROSA",
            "SAÑA",
            "LA VICTORIA",
            "CAYALTI",
            "PATAPO",
            "POMALCA",
            "PUCALA",
            "TUMAN"
        ],
        "FERREÑAFE": [
            "FERREÑAFE",
            "INCAHUASI",
            "CAÑARIS",
            "PITIPO",
            "PUEBLO NUEVO",
            "MANUEL ANTONIO MESONES MURO"
        ],
        "LAMBAYEQUE": [
            "LAMBAYEQUE",
            "CHOCHOPE",
            "ILLIMO",
            "JAYANCA",
            "MOCHUMI",
            "MORROPE",
            "MOTUPE",
            "OLMOS",
            "PACORA",
            "SALAS",
            "SAN JOSE",
            "TUCUME"
        ]
    },
    "LIMA": {
        "LIMA": [
            "LIMA",
            "ANCON",
            "ATE",
            "BREÑA",
            "CARABAYLLO",
            "COMAS",
            "CHACLACAYO",
            "CHORRILLOS",
            "LA VICTORIA",
            "LA MOLINA",
            "LINCE",
            "LURIGANCHO",
            "LURIN",
            "MAGDALENA DEL MAR",
            "MIRAFLORES",
            "PACHACAMAC",
            "PUEBLO LIBRE",
            "PUCUSANA",
            "PUENTE PIEDRA",
            "PUNTA HERMOSA",
            "PUNTA NEGRA",
            "RIMAC",
            "SAN BARTOLO",
            "SAN ISIDRO",
            "BARRANCO",
            "SAN MARTIN DE PORRES",
            "SAN MIGUEL",
            "SANTA MARIA DEL MAR",
            "SANTA ROSA",
            "SANTIAGO DE SURCO",
            "SURQUILLO",
            "VILLA MARIA DEL TRIUNFO",
            "JESUS MARIA",
            "INDEPENDENCIA",
            "EL AGUSTINO",
            "SAN JUAN DE MIRAFLORES",
            "SAN JUAN DE LURIGANCHO",
            "SAN LUIS",
            "CIENEGUILLA",
            "SAN BORJA",
            "VILLA EL SALVADOR",
            "LOS OLIVOS",
            "SANTA ANITA"
        ],
        "CAJATAMBO": [
            "CAJATAMBO",
            "COPA",
            "GORGOR",
            "HUANCAPON",
            "MANAS"
        ],
        "CANTA": [
            "CANTA",
            "ARAHUAY",
            "HUAMANTANGA",
            "HUAROS",
            "LACHAQUI",
            "SAN BUENAVENTURA",
            "SANTA ROSA DE QUIVES"
        ],
        "CAÑETE": [
            "SAN VICENTE DE CAÑETE",
            "CALANGO",
            "CERRO AZUL",
            "COAYLLO",
            "CHILCA",
            "IMPERIAL",
            "LUNAHUANA",
            "MALA",
            "NUEVO IMPERIAL",
            "PACARAN",
            "QUILMANA",
            "SAN ANTONIO",
            "SAN LUIS",
            "SANTA CRUZ DE FLORES",
            "ZUÑIGA",
            "ASIA"
        ],
        "HUAURA": [
            "HUACHO",
            "AMBAR",
            "CALETA DE CARQUIN",
            "CHECRAS",
            "HUALMAY",
            "HUAURA",
            "LEONCIO PRADO",
            "PACCHO",
            "SANTA LEONOR",
            "SANTA MARIA",
            "SAYAN",
            "VEGUETA"
        ],
        "HUAROCHIRI": [
            "MATUCANA",
            "ANTIOQUIA",
            "CALLAHUANCA",
            "CARAMPOMA",
            "SAN PEDRO DE CASTA",
            "CUENCA",
            "CHICLA",
            "HUANZA",
            "HUAROCHIRI",
            "LAHUAYTAMBO",
            "LANGA",
            "MARIATANA",
            "RICARDO PALMA",
            "SAN ANDRES DE TUPICOCHA",
            "SAN ANTONIO",
            "SAN BARTOLOME",
            "SAN DAMIAN",
            "SANGALLAYA",
            "SAN JUAN DE TANTARANCHE",
            "SAN LORENZO DE QUINTI",
            "SAN MATEO",
            "SAN MATEO DE OTAO",
            "SAN PEDRO DE HUANCAYRE",
            "SANTA CRUZ DE COCACHACRA",
            "SANTA EULALIA",
            "SANTIAGO DE ANCHUCAYA",
            "SANTIAGO DE TUNA",
            "SANTO DOMINGO DE LOS OLLEROS",
            "SURCO",
            "HUACHUPAMPA",
            "SAN PEDRO LARAOS",
            "SAN JUAN DE IRIS"
        ],
        "YAUYOS": [
            "YAUYOS",
            "ALIS",
            "AYAUCA",
            "AYAVIRI",
            "AZANGARO",
            "CACRA",
            "CARANIA",
            "COCHAS",
            "COLONIA",
            "CHOCOS",
            "HUAMPARA",
            "HUANCAYA",
            "HUANGASCAR",
            "HUANTAN",
            "HUAÑEC",
            "LARAOS",
            "LINCHA",
            "MIRAFLORES",
            "OMAS",
            "QUINCHES",
            "QUINOCAY",
            "SAN JOAQUIN",
            "SAN PEDRO DE PILAS",
            "TANTA",
            "TAURIPAMPA",
            "TUPE",
            "TOMAS",
            "VIÑAC",
            "VITIS",
            "HONGOS",
            "MADEAN",
            "PUTINZA",
            "CATAHUASI"
        ],
        "HUARAL": [
            "HUARAL",
            "ATAVILLOS ALTO",
            "ATAVILLOS BAJO",
            "AUCALLAMA",
            "CHANCAY",
            "IHUARI",
            "LAMPIAN",
            "PACARAOS",
            "SAN MIGUEL DE ACOS",
            "VEINTISIETE DE NOVIEMBRE",
            "SANTA CRUZ DE ANDAMARCA",
            "SUMBILCA"
        ],
        "BARRANCA": [
            "BARRANCA",
            "PARAMONGA",
            "PATIVILCA",
            "SUPE",
            "SUPE PUERTO"
        ],
        "OYON": [
            "OYON",
            "NAVAN",
            "CAUJUL",
            "ANDAJES",
            "PACHANGARA",
            "COCHAMARCA"
        ]
    },
    "LORETO": {
        "MAYNAS": [
            "IQUITOS",
            "ALTO NANAY",
            "FERNANDO LORES",
            "LAS AMAZONAS",
            "MAZAN",
            "NAPO",
            "TORRES CAUSANA",
            "INDIANA",
            "PUNCHANA",
            "BELEN",
            "SAN JUAN BAUTISTA"
        ],
        "ALTO AMAZONAS": [
            "YURIMAGUAS",
            "BALSAPUERTO",
            "JEBEROS",
            "LAGUNAS",
            "SANTA CRUZ",
            "TENIENTE CESAR LOPEZ ROJAS"
        ],
        "LORETO": [
            "NAUTA",
            "PARINARI",
            "TIGRE",
            "URARINAS",
            "TROMPETEROS"
        ],
        "REQUENA": [
            "REQUENA",
            "ALTO TAPICHE",
            "CAPELO",
            "EMILIO SAN MARTIN",
            "MAQUIA",
            "PUINAHUA",
            "SAQUENA",
            "SOPLIN",
            "TAPICHE",
            "JENARO HERRERA",
            "YAQUERANA"
        ],
        "UCAYALI": [
            "CONTAMANA",
            "VARGAS GUERRA",
            "PADRE MARQUEZ",
            "PAMPA HERMOSA",
            "SARAYACU",
            "INAHUAYA"
        ],
        "MARISCAL RAMON CASTILLA": [
            "RAMON CASTILLA",
            "PEBAS",
            "YAVARI",
            "SAN PABLO",
            "SANTA ROSA DE LORETO"
        ],
        "DATEM DEL MARAÑON": [
            "BARRANCA",
            "ANDOAS",
            "CAHUAPANAS",
            "MANSERICHE",
            "MORONA",
            "PASTAZA"
        ],
        "PUTUMAYO": [
            "PUTUMAYO",
            "ROSA PANDURO",
            "TENIENTE MANUEL CLAVERO",
            "YAGUAS"
        ]
    },
    "MADRE DE DIOS": {
        "TAMBOPATA": [
            "TAMBOPATA",
            "INAMBARI",
            "LAS PIEDRAS",
            "LABERINTO"
        ],
        "MANU": [
            "MANU",
            "FITZCARRALD",
            "MADRE DE DIOS",
            "HUEPETUHE"
        ],
        "TAHUAMANU": [
            "IÑAPARI",
            "IBERIA",
            "TAHUAMANU"
        ]
    },
    "MOQUEGUA": {
        "MARISCAL NIETO": [
            "MOQUEGUA",
            "CARUMAS",
            "CUCHUMBAYA",
            "SAN CRISTOBAL",
            "TORATA",
            "SAMEGUA",
            "SAN ANTONIO"
        ],
        "GENERAL SANCHEZ CERRO": [
            "OMATE",
            "COALAQUE",
            "CHOJATA",
            "ICHUÑA",
            "LA CAPILLA",
            "LLOQUE",
            "MATALAQUE",
            "PUQUINA",
            "QUINISTAQUILLAS",
            "UBINAS",
            "YUNGA"
        ],
        "ILO": [
            "ILO",
            "EL ALGARROBAL",
            "PACOCHA"
        ]
    },
    "PASCO": {
        "PASCO": [
            "CHAUPIMARCA",
            "HUACHON",
            "HUARIACA",
            "HUAYLLAY",
            "NINACACA",
            "PALLANCHACRA",
            "PAUCARTAMBO",
            "SAN FRANCISCO DE ASIS DE YARUSYACAN",
            "SIMON BOLIVAR",
            "TICLACAYAN",
            "TINYAHUARCO",
            "VICCO",
            "YANACANCHA"
        ],
        "DANIEL ALCIDES CARRION": [
            "YANAHUANCA",
            "CHACAYAN",
            "GOYLLARISQUIZGA",
            "PAUCAR",
            "SAN PEDRO DE PILLAO",
            "SANTA ANA DE TUSI",
            "TAPUC",
            "VILCABAMBA"
        ],
        "OXAPAMPA": [
            "OXAPAMPA",
            "CHONTABAMBA",
            "HUANCABAMBA",
            "PUERTO BERMUDEZ",
            "VILLA RICA",
            "POZUZO",
            "PALCAZU",
            "CONSTITUCION"
        ]
    },
    "PIURA": {
        "PIURA": [
            "PIURA",
            "CASTILLA",
            "CATACAOS",
            "LA ARENA",
            "LA UNION",
            "LAS LOMAS",
            "TAMBO GRANDE",
            "CURA MORI",
            "EL TALLAN",
            "VEINTISEIS DE OCTUBRE"
        ],
        "AYABACA": [
            "AYABACA",
            "FRIAS",
            "LAGUNAS",
            "MONTERO",
            "PACAIPAMPA",
            "SAPILLICA",
            "SICCHEZ",
            "SUYO",
            "JILILI",
            "PAIMAS"
        ],
        "HUANCABAMBA": [
            "HUANCABAMBA",
            "CANCHAQUE",
            "HUARMACA",
            "SONDOR",
            "SONDORILLO",
            "EL CARMEN DE LA FRONTERA",
            "SAN MIGUEL DE EL FAIQUE",
            "LALAQUIZ"
        ],
        "MORROPON": [
            "CHULUCANAS",
            "BUENOS AIRES",
            "CHALACO",
            "MORROPON",
            "SALITRAL",
            "SANTA CATALINA DE MOSSA",
            "SANTO DOMINGO",
            "LA MATANZA",
            "YAMANGO",
            "SAN JUAN DE BIGOTE"
        ],
        "PAITA": [
            "PAITA",
            "AMOTAPE",
            "ARENAL",
            "LA HUACA",
            "COLAN",
            "TAMARINDO",
            "VICHAYAL"
        ],
        "SULLANA": [
            "SULLANA",
            "BELLAVISTA",
            "LANCONES",
            "MARCAVELICA",
            "MIGUEL CHECA",
            "QUERECOTILLO",
            "SALITRAL",
            "IGNACIO ESCUDERO"
        ],
        "TALARA": [
            "PARIÑAS",
            "EL ALTO",
            "LA BREA",
            "LOBITOS",
            "MANCORA",
            "LOS ORGANOS"
        ],
        "SECHURA": [
            "SECHURA",
            "VICE",
            "BERNAL",
            "BELLAVISTA DE LA UNION",
            "CRISTO NOS VALGA",
            "RINCONADA-LLICUAR"
        ]
    },
    "PUNO": {
        "PUNO": [
            "PUNO",
            "ACORA",
            "ATUNCOLLA",
            "CAPACHICA",
            "COATA",
            "CHUCUITO",
            "HUATA",
            "MAÑAZO",
            "PAUCARCOLLA",
            "PICHACANI",
            "SAN ANTONIO",
            "TIQUILLACA",
            "VILQUE",
            "PLATERIA",
            "AMANTANI"
        ],
        "AZANGARO": [
            "AZANGARO",
            "ACHAYA",
            "ARAPA",
            "ASILLO",
            "CAMINACA",
            "CHUPA",
            "JOSE DOMINGO CHOQUEHUANCA",
            "MUÑANI",
            "POTONI",
            "SAMAN",
            "SAN ANTON",
            "SAN JOSE",
            "SAN JUAN DE SALINAS",
            "SANTIAGO DE PUPUJA",
            "TIRAPATA"
        ],
        "CARABAYA": [
            "MACUSANI",
            "AJOYANI",
            "AYAPATA",
            "COASA",
            "CORANI",
            "CRUCERO",
            "ITUATA",
            "OLLACHEA",
            "SAN GABAN",
            "USICAYOS"
        ],
        "CHUCUITO": [
            "JULI",
            "DESAGUADERO",
            "HUACULLANI",
            "PISACOMA",
            "POMATA",
            "ZEPITA",
            "KELLUYO"
        ],
        "HUANCANE": [
            "HUANCANE",
            "COJATA",
            "INCHUPALLA",
            "PUSI",
            "ROSASPATA",
            "TARACO",
            "VILQUE CHICO",
            "HUATASANI"
        ],
        "LAMPA": [
            "LAMPA",
            "CABANILLA",
            "CALAPUJA",
            "NICASIO",
            "OCUVIRI",
            "PALCA",
            "PARATIA",
            "PUCARA",
            "SANTA LUCIA",
            "VILAVILA"
        ],
        "MELGAR": [
            "AYAVIRI",
            "ANTAUTA",
            "CUPI",
            "LLALLI",
            "MACARI",
            "NUÑOA",
            "ORURILLO",
            "SANTA ROSA",
            "UMACHIRI"
        ],
        "SANDIA": [
            "SANDIA",
            "CUYOCUYO",
            "LIMBANI",
            "PHARA",
            "PATAMBUCO",
            "QUIACA",
            "SAN JUAN DEL ORO",
            "YANAHUAYA",
            "ALTO INAMBARI",
            "SAN PEDRO DE PUTINA PUNCO"
        ],
        "SAN ROMAN": [
            "JULIACA",
            "CABANA",
            "CABANILLAS",
            "CARACOTO",
            "SAN MIGUEL"
        ],
        "YUNGUYO": [
            "YUNGUYO",
            "UNICACHI",
            "ANAPIA",
            "COPANI",
            "CUTURAPI",
            "OLLARAYA",
            "TINICACHI"
        ],
        "SAN ANTONIO DE PUTINA": [
            "PUTINA",
            "PEDRO VILCA APAZA",
            "QUILCAPUNCU",
            "ANANEA",
            "SINA"
        ],
        "EL COLLAO": [
            "ILAVE",
            "PILCUYO",
            "SANTA ROSA",
            "CAPAZO",
            "CONDURIRI"
        ],
        "MOHO": [
            "MOHO",
            "CONIMA",
            "TILALI",
            "HUAYRAPATA"
        ]
    },
    "SAN MARTIN": {
        "MOYOBAMBA": [
            "MOYOBAMBA",
            "CALZADA",
            "HABANA",
            "JEPELACIO",
            "SORITOR",
            "YANTALO"
        ],
        "HUALLAGA": [
            "SAPOSOA",
            "PISCOYACU",
            "SACANCHE",
            "TINGO DE SAPOSOA",
            "ALTO SAPOSOA",
            "EL ESLABON"
        ],
        "LAMAS": [
            "LAMAS",
            "BARRANQUITA",
            "CAYNARACHI",
            "CUÑUMBUQUI",
            "PINTO RECODO",
            "RUMISAPA",
            "SHANAO",
            "TABALOSOS",
            "ZAPATERO",
            "ALONSO DE ALVARADO",
            "SAN ROQUE DE CUMBAZA"
        ],
        "MARISCAL CACERES": [
            "JUANJUI",
            "CAMPANILLA",
            "HUICUNGO",
            "PACHIZA",
            "PAJARILLO"
        ],
        "RIOJA": [
            "RIOJA",
            "POSIC",
            "YORONGOS",
            "YURACYACU",
            "NUEVA CAJAMARCA",
            "ELIAS SOPLIN VARGAS",
            "SAN FERNANDO",
            "PARDO MIGUEL",
            "AWAJUN"
        ],
        "SAN MARTIN": [
            "TARAPOTO",
            "ALBERTO LEVEAU",
            "CACATACHI",
            "CHAZUTA",
            "CHIPURANA",
            "EL PORVENIR",
            "HUIMBAYOC",
            "JUAN GUERRA",
            "MORALES",
            "PAPAPLAYA",
            "SAN ANTONIO",
            "SAUCE",
            "SHAPAJA",
            "LA BANDA DE SHILCAYO"
        ],
        "BELLAVISTA": [
            "BELLAVISTA",
            "SAN RAFAEL",
            "SAN PABLO",
            "ALTO BIAVO",
            "HUALLAGA",
            "BAJO BIAVO"
        ],
        "TOCACHE": [
            "TOCACHE",
            "NUEVO PROGRESO",
            "POLVORA",
            "SHUNTE",
            "UCHIZA",
            "SANTA LUCIA"
        ],
        "PICOTA": [
            "PICOTA",
            "BUENOS AIRES",
            "CASPIZAPA",
            "PILLUANA",
            "PUCACACA",
            "SAN CRISTOBAL",
            "SAN HILARION",
            "TINGO DE PONASA",
            "TRES UNIDOS",
            "SHAMBOYACU"
        ],
        "EL DORADO": [
            "SAN JOSE DE SISA",
            "AGUA BLANCA",
            "SHATOJA",
            "SAN MARTIN",
            "SANTA ROSA"
        ]
    },
    "TACNA": {
        "TACNA": [
            "TACNA",
            "CALANA",
            "INCLAN",
            "PACHIA",
            "PALCA",
            "POCOLLAY",
            "SAMA",
            "ALTO DE LA ALIANZA",
            "CIUDAD NUEVA",
            "CORONEL GREGORIO ALBARRACIN LANCHIPA",
            "LA YARADA LOS PALOS"
        ],
        "TARATA": [
            "TARATA",
            "HEROES ALBARRACIN",
            "ESTIQUE",
            "ESTIQUE PAMPA",
            "SITAJARA",
            "SUSAPAYA",
            "TARUCACHI",
            "TICACO"
        ],
        "JORGE BASADRE": [
            "LOCUMBA",
            "ITE",
            "ILABAYA"
        ],
        "CANDARAVE": [
            "CANDARAVE",
            "CAIRANI",
            "CURIBAYA",
            "HUANUARA",
            "QUILAHUANI",
            "CAMILACA"
        ]
    },
    "TUMBES": {
        "TUMBES": [
            "TUMBES",
            "CORRALES",
            "LA CRUZ",
            "PAMPAS DE HOSPITAL",
            "SAN JACINTO",
            "SAN JUAN DE LA VIRGEN"
        ],
        "CONTRALMIRANTE VILLAR": [
            "ZORRITOS",
            "CASITAS",
            "CANOAS DE PUNTA SAL"
        ],
        "ZARUMILLA": [
            "ZARUMILLA",
            "MATAPALO",
            "PAPAYAL",
            "AGUAS VERDES"
        ]
    },
    "CALLAO": {
        "CALLAO": [
            "CALLAO",
            "BELLAVISTA",
            "LA PUNTA",
            "CARMEN DE LA LEGUA-REYNOSO",
            "LA PERLA",
            "VENTANILLA",
            "MI PERU"
        ]
    },
    "UCAYALI": {
        "CORONEL PORTILLO": [
            "CALLERIA",
            "YARINACOCHA",
            "MASISEA",
            "CAMPOVERDE",
            "IPARIA",
            "NUEVA REQUENA",
            "MANANTAY"
        ],
        "PADRE ABAD": [
            "PADRE ABAD",
            "IRAZOLA",
            "CURIMANA",
            "NESHUYA",
            "ALEXANDER VON HUMBOLDT",
            "BOQUERON",
            "HUIPOCA"
        ],
        "ATALAYA": [
            "RAIMONDI",
            "TAHUANIA",
            "YURUA",
            "SEPAHUA"
        ],
        "PURUS": [
            "PURUS"
        ]
    }
} as const;
